[project]
name = "aclanthology.org"
version = "2026.2.1"
requires-python = ">=3.10"
dependencies = ["acl-anthology"]

[tool.uv.sources]
acl-anthology = { workspace = true }

[tool.uv.workspace]
members = ["python/"]

[tool.ruff]
line-length = 90
target-version = 'py310'
