[tool.black]
line-length = 90
target-version = ['py310', 'py311']
skip-string-normalization = false

[tool.ruff]
ignore = ['E501']  # "Line too long" is black's job
target-version = 'py310'

[tool.poetry]
name = "acl-anthology-py"
packages = [
    { include = "acl_anthology" },
]
version = "0.1.0"
description = "A library for accessing the ACL Anthology"
authors = ["Marcel Bollmann <marcel@bollmann.me>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/mbollmann/acl-anthology-py"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Interface Engine/Protocol Translator",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.poetry.dependencies]
python = "^3.10"
docopt = "^0.6.2"
latexcodec = "^2.0.1"
lxml = "^4.9.2"
PyYAML = "^6.0"
app-paths = "^0.0.7"
diskcache = "^5.6.1"
rich = "^13.3.5"

[tool.poetry.dev-dependencies]
black = "^23.3.0"
pytest = "^7.3.1"
pytest-cov = "^4.0.0"
ruff = "^0.0.269"
pre-commit = "^3.3.2"
richbench = "^1.0.3"

[tool.poetry.group.dev.dependencies]
mkdocs = "^1.4.3"
mkdocstrings = {extras = ["python"], version = "^0.22.0"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
